version: '2'
services:
  tree2neo:
    build: .
    image: tree2neo
    container_name: tree2neo
    environment:
      DB: db
    depends_on:
      - db
  db:
    image: neo4j:3.0.4
    container_name: tree2neo-db
    volumes_from:
      - dc:rw
    environment:
      NEO4J_AUTH: none
    ports:
      - "7687:7687"
      - "7474:7474"
    depends_on:
      - dc
  dc:
      build: dc/
      container_name: tree2neo-dc
